# Generated by Django 3.0.2 on 2020-04-22 19:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('pkgid', models.AutoField(primary_key=True, serialize=False)),
                ('truckid', models.IntegerField(blank=True, null=True)),
                ('userid', models.IntegerField(default=0)),
                ('ups_username', models.CharField(blank=True, max_length=50, null=True)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('item_name', models.CharField(default='', max_length=100)),
                ('item_id', models.IntegerField(default=0)),
                ('purchase_num', models.IntegerField(default=1)),
                ('is_enough', models.BooleanField(default=False)),
                ('is_order_placed', models.BooleanField(default=False)),
                ('is_packed', models.BooleanField(default=False)),
                ('is_truck_arrived', models.BooleanField(default=False)),
                ('is_loaded', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('whid', models.IntegerField(default=1)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('whid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=10)),
                ('y', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
