# Generated by Django 3.0.2 on 2020-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_web', '0002_auto_20200417_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACommandsToWorld',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('acommand_type', models.CharField(max_length=30)),
                ('acommand', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AMsgToUPS',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('amsg_type', models.CharField(max_length=30)),
                ('amsg', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_description',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='upsid',
            new_name='ups_username',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
